export enum JobErrorCode {
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  JOB_ALREADY_RUNNING = 'JOB_ALREADY_RUNNING',
  JOB_CANNOT_BE_PAUSED = 'JOB_CANNOT_BE_PAUSED',
  JOB_CANNOT_BE_RESUMED = 'JOB_CANNOT_BE_RESUMED',
  JOB_CANNOT_BE_CANCELLED = 'JOB_CANNOT_BE_CANCELLED',
  JOB_PROCESSING_FAILED = 'JOB_PROCESSING_FAILED',
  INVALID_INPUT_FORMAT = 'INVALID_INPUT_FORMAT',
  PROVIDER_NOT_SUPPORTED = 'PROVIDER_NOT_SUPPORTED',
}